### ISSUE TITLE
What is test-connection?

### ISSUE THREAD

**Issue by Gooberpatrol66** [plattfot/baksnapper#1]
When I run baksnapper I get bash: test-connection: command not found

**Comment by plattfot** [comment]
Did you run it with an ssh address?
If so did you properly setup the backup server to use only use baksnapperd when using that ssh key?
See: https://github.com/plattfot/baksnapper#remote-backup-over-ssh

The test-connection is a command in baksnapperd to simply test if the connection works. By the looks of that error, it send that command directly to a bash shell and not to the baksnapperd.

**Comment by Gooberpatrol66** [comment]
`gentooserver /home/nathan # baksnapper --config config --all gentoodesktop:/run/media/nathan/3fc8c98e-3af3-4900-808a-4a3b366bd71c/`

```
gentoodesktop /home/nathan # cat /root/.ssh/authorized_keys
ssh-rsa <key> nathan@gentoolaptop
command="baksnapperd $SSH_ORIGINAL_COMMAND" ssh-rsa <key> root@gentooserver-2018-09-09


```

**Comment by Gooberpatrol66** [comment]
```
gentooserver ~ # (ssh gentoodesktop test-connection) && echo "Connection works"
Password: 
bash: test-connection: command not found
gentooserver ~ # whoami
root
```

**Comment by plattfot** [comment]
I added the option --private-key in v0.9.0, which you can specify the key to use. See if that works.

You can also test it with
(ssh -i <key> gentoodesktop test-connection) && echo "Connection works"

**Comment by Gooberpatrol66** [comment]
That fixed it.
