### ISSUE TITLE
Arch install instructions outdated

### ISSUE THREAD

**Issue by ni-ka** [plattfot/baksnapper#14]
Hi,

Just trying your tool on manjaro. The arch install instructions don't work.

Instead I cloned https://github.com/plattfot/baksnapper-aur/blob/master/PKGBUILD and bumped the version manually to 2.2.0

Cheers!

**Comment by plattfot** [comment]
Hi,

Thank you for pointing that out. The build instructions should now be up to date. Although bumping up the baksnapper-aur also works. Which reminds me that I should probably archive that one as I moved the PKGBUILD to this repo.

**Comment by ni-ka** [comment]
Hi, Thanks for quick response - I had not seen the PKGBUILD in the subfolder
