### ISSUE TITLE
bad array subscript

### ISSUE THREAD

**Issue by mcteixeira** [plattfot/baksnapper#16]
Hi 

I'm getting the error below when trying to run the script:
_/usr/bin/baksnapper: line 406: src_snapshots: bad array subscript_

Command that I'm running is below:
_baksnapper --config root --all --prune /mnt/backups_

I think the error occurs when there are no snapshots available to backup

Thank you

**Comment by plattfot** [comment]
Hi
Thank you for reporting this issue.

Are you able to test out the PR #17? That should fix this.

**Comment by mcteixeira** [comment]
Hi 

The issue is fixed.

Thanks!
