### ISSUE TITLE
unrecognized command, bailing out

### ISSUE THREAD

**Issue by Gooberpatrol66** [plattfot/baksnapper#4]
```
baksnapper --config config --all --prune url.com:/media/backup --private-key /root/.ssh/baksnapperd_rsa
Incremental backup
At subvol /media/store/.snapshots/2621/snapshot
At snapshot snapshot
ERROR: cannot find parent subvolume
[ERROR] Unrecognized command, bailing out!
[ERROR] Failed to send snapshot!
```

What is this?

**Comment by plattfot** [comment]
Looks like it's failing to find the parent subvolume which its basing the incremental snapshot on and failing. Make sure the snapshots are ok.

As for the unrecognized command.
There was a breaking change in version 1.0.0 in baksnapperd. Are you mixing 0.x and 1.0.x versions between client and server?

**Comment by Gooberpatrol66** [comment]
I changed a lot of things. Closing because it's no longer relevant, thanks.
