### ISSUE TITLE
Feature request: directory pointing to latest snapshot

### ISSUE THREAD

**Issue by Gooberpatrol66** [plattfot/baksnapper#6]
I am setting up offsite backup and would like to just backup the latest copy of the data. Would it be possible for baksnapper to create a "latest" folder in the snapshots directory and have it point to the latest snapshot?

Thanks.

**Comment by plattfot** [comment]
It would be possible to create a snapshot called `latest` that will point to the latest snapshot, it would still need to keep the original snapshot(s) it backed up though. As the logic right now is to compare the name of the snapshot directories in the backup and the original location to determine what needs to be transferred.

To do it properly it would need to start reading the `info.xml` for each snapshot to figure out the snapshot number and that way decouple the directory name with the snapshot. Which I find to be a cleaner solution. But will take longer to implement.

I'm quite swamp with work right now so I won't have time to work on this at least this week.

I also want to implement some sort of testing before making bigger changes to the code. To make sure I don't break anything.
